apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-lightblue-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: "registry.eu-gb.bluemix.net/accdevimages/customer"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-lightblue-service
  labels:
    app: customer
spec:
  type: NodePort
  selector:
    app: customer
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30114
